### ISSUE TITLE
8th of June. The Minskins.

### ISSUE THREAD

**Issue by WinterCore** [wrakc/newsweek-clone#1]
Great project. 👌 Good luck with finishing it.
Suggestions:
- Check this [sticky bootstrap](https://getbootstrap.com/docs/4.0/utilities/position/#sticky-top). You might want to apply it for the header
- Just a reminder. You're using the `row` bootstrap class without adding `col` classes to the children (line 32). Here's the [docs](https://getbootstrap.com/docs/4.0/layout/grid/)

And here's a happy bear.

<pre>
                  _         _
 .-""-.          ( )-"```"-( )          .-""-.
/ O O  \          /         \          /  O O \
|O .-.  \        /   0 _ 0   \        /  .-. O|
\ (   )  '.    _|     (_)     |     .'  (   ) /
 '.`-'     '-./ |             |`\.-'     '-'.'
   \         |  \   \     /   /  |         /
    \        \   '.  '._.'  .'   /        /
     \        '.   `'-----'`   .'        /
      \   .'    '-._        .-'\   '.   /
       |/`          `'''''')    )    `\|
       /                  (    (      ,\
      ;                    \    '-..-'/ ;
      |                     '.       /  |
      |                       `'---'`   |
      ;                                 ;
       \                               /
        `.                           .'
          '-._                   _.-'
           __/`"  '  - - -  ' "`` \__
         /`            /^\           `\
         \(          .'   '.         )/
          '.(__(__.-'       '.__)__).'
</pre>

**Comment by carlosveigadev** [comment]
Thanks for the help guys!
