### ISSUE TITLE
11th of June. The Minskins.

### ISSUE THREAD

**Issue by WinterCore** [wrakc/newsweek-clone#2]
The mobile version looks great.  I hope everything goes well making it responsive.

And here's an owl

<pre>
  __________
 / ___  ___ \
/ / @ \/ @ \ \
\ \___/\___/ /\
 \____\/____/||
 /     /\\\\\//
|     |\\\\\\
 \      \\\\\\
   \______/\\\\
    _||_||_

</pre>

**Comment by carlosveigadev** [comment]
Thanks for the help!
